services:
  - type: web
    name: springboot-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean compile -DskipTests
    startCommand: ./mvnw spring-boot:run
    rootDir: fake-news-detector-backend
    branch: master

  - type: web
    name: python-ml-api
    env: python
    plan: free
    rootDir: ml-api
    branch: master
    buildCommand: |
      python3 -m venv venv
      . venv/bin/activate
      pip3 install --no-cache-dir -r requirements.txt
    startCommand: |
      . venv/bin/activate
      python3 app.py
